#!/bin/bash

help (){
echo "site map generator for websites that serve static content or autogenerated indexes from Nginx"
echo "Usage: the-place-you-love.sh <my.example.com> <dir>"
echo ""
echo "NOTE: don't add '/' in both the url and the directory"
echo "Example: the-place-you-love.sh google.com Documents"
}

get_name(){
	echo $1 | rev | cut -d "/" -f 1 | rev
}

gen (){
echo "<ul>"
	for file in $1/*
	do
		if [ -d $file ]
		then
				echo "<li><a href='$BASE_URL${file}'><h4>$(get_name $(echo $file | tr ' ' '+')|tr '+' ' ')<h4></a></li>"
				gen $file
		else
		echo "<li><a href='$BASE_URL${file}'>"
		echo "$(get_name $(echo $file | tr ' ' '+')|tr '+' ' ')</a></li>"
		file=$(echo $file | tr " " "+" )

		fi
	done
echo "</ul>"
}

if [ -z $1 ]
then
	help
elif [ -z $2 ]
then	help
else
	BASE_URL=$1/
	echo "<h1> Site map</h2>"
	echo "<h3> Please note that the site map is autogerated by a hackish script so it wont be perfect.</h3>"
	gen $2
fi
